name: Run

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends curl ca-certificates patch make binaryen wabt unzip
        sudo mkdir /opt/wasi-sdk
        curl -sSfL $WASI_SDK_URL | sudo tar zxf - -C /opt/wasi-sdk --strip-components 1
        echo /opt/wasi-sdk/bin >> $GITHUB_PATH
        curl -fsSL https://deno.land/x/install/install.sh | sh
        echo ~/.deno >> $GITHUB_PATH
      env:
        WASI_SDK_URL: 'https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk-12.0-linux.tar.gz'

    - name: Version
      run: |
        clang --version
        wasm2wat --version
        wasm-opt --version
        deno --version

    - name: Run
      run: |
        make test WASI_SYSROOT=$WASI_SYSROOT -C 01_const/
        make test WASI_SYSROOT=$WASI_SYSROOT -C 02_const_overwirte/
        make test WASI_SYSROOT=$WASI_SYSROOT -C 03_stack/
        make test WASI_SYSROOT=$WASI_SYSROOT -C 04_messedup/
      env:
        WASI_SYSROOT: /opt/wasi-sdk/share/wasi-sysroot/
